name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  FTP-Transfer:
    name: Tranfer files via FTP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: joutvhu/ftp-transfer@v1
        with:
          host: gvam1064.siteground.biz
          port: 21
          username: nina_home@greenworkforceconnect.org
          password: ${{ secrets.FTP_PASSWORD }}
          commands: |
            get public_html/wp-content/plugins/irec-green-connect wp-content/plugins/irec-green-connect 
            put wp-content/plugins/irec-green-connect public_html/wp-content/plugins/irec-green-gconnect.new
