name: Production Deployment
on:
  push:
    branches:
      - main

jobs:
  # FTP Deploy
  deploy:
    name: 🚀 Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SFTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: gvam1064.siteground.biz
          username: nina@greenworkforceconnect.org
          password: ${{ secrets.FTP_PROD_PASSWORD }}
          server-dir: greenworkforceconnect.org/public_html/
          port: 21
