name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  FTP-Transfer:
    name: Tranfer files via FTP
    runs-on: ubuntu-latest

    steps:
      - uses: joutvhu/ftp-transfer@v1
        with:
          host: gvam1064.siteground.biz
          port: 21
          username: nina_home@greenworkforceconnect.org
          password: ${{ secrets.FTP_PASSWORD }}
          commands: |
            ls
            get ./public_html/wp-content/plugins/irec-green-connect ./wp-content/plugins/irec-green-connect 
            put ./wp-content/plugins/irec-green-connect ./public_html/wp-content/plugins/irec-green-gconnect.new
            rename ./public_html/plugins/wp-content/irec-green-connect ./public_html/plugins/wp-content/irec-green-connect.old
            rename ./public_html/plugins/wp-content/irec-green-gconnect.new ./public_html/plugins/wp-content/irec-green-gconnect
            delete ./public_html/wp-content/plugins/irec-green-connect.old
