name: Run Cypress Tests

on:
  schedule:
    # Runs every Monday at midnight (00:00 UTC)
    - cron: '0 0 * * MON'
  # Optional: Add manual trigger
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      CYPRESS_AUTH_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
      CYPRESS_AUTH_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn' # Enable caching for faster installations

      # Install dependencies
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn cypress verify

      # Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/**/*.cy.js
        env:
          # Pass any additional environment variables needed for tests
          CYPRESS_BASE_URL: 'https://greenworkforceconnect.org'
          CYPRESS_AUTH_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          CYPRESS_AUTH_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}

      # Upload test results (only if tests fail)
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure() # Only upload on failure
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7 # Keep for 7 days

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: failure() # Only upload on failure
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7 # Keep for 7 days

      # Optional: Add notification on failure
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Cypress Tests Failed',
              body: `Cypress tests failed in run ${context.runId}. [View run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
            })
